---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "draw-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draw-app
  template:
    metadata:
      labels:
        app: draw-app
    spec:
      containers:
        - name: draw-app
          image: "gcr.io/tech-rnd-project/faz-todo:tagversion"
          ports:
            - containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: draw-app
spec:
  ports:
    - port: 1234
      targetPort: 1234
  type: LoadBalancer
  selector:
    app: draw-app
